version: 2

default: &default
  docker:
  - image: circleci/openjdk:8-jdk

  working_directory: ~/repo

  environment:
    MAVEN_OPTS: -Xmx1200m

jobs:
  build:
    <<: *default

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    - run: mvn test